entity.product.view:
  title: 'View'
  route_name: entity.product.canonical
  base_route: entity.product.canonical
entity.product.edit_form:
  title: 'Edit'
  route_name: entity.product.edit_form
  base_route: entity.product.canonical
entity.product.delete_form:
  title: 'Delete'
  route_name: entity.product.delete_form
  base_route: entity.product.canonical
  weight: 10
entity.product.collection:
  title: 'product'
  route_name: entity.product.collection
  base_route: system.admin_content
  weight: 10
  
entity.product_type.edit_form:
  title: 'Edit'
  route_name: entity.product_type.edit_form
  base_route: entity.product_type.edit_form
entity.product_type.collection:
  title: 'List'
  route_name: entity.product_type.collection
  base_route: entity.product_type.collection
