<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
/*function product_catalog_preprocess_node(array &$variables) {
  $node = $variables['node'];

  if ($node instanceof EntityInterface && $node->hasField('field_layout_theme')) {
    $value = $node->get('field_layout_theme')->value;

    if (!empty($value)) {
      // Add a CSS class to the node wrapper.
      $variables['attributes']['class'][] = 'layout-theme--' . $value;
    }
  }
}*/