<?php

/**
 * @file
 * Primary module hooks for custom_entity_example module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function custom_entity_example_theme(): array {
  return [
    'custom_entity_node' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for custom_entity_node templates.
 *
 * Default template: custom-entity-node.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the custom_entity_node information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_custom_entity_node(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function custom_entity_example_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish custom_entity_nodes.
      $storage = \Drupal::entityTypeManager()->getStorage('custom_entity_node');
      $custom_entity_node_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($custom_entity_node_ids) as $custom_entity_node) {
        $custom_entity_node->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize custom_entity_nodes.
      $storage = \Drupal::entityTypeManager()->getStorage('custom_entity_node');
      $custom_entity_node_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($custom_entity_node_ids) as $custom_entity_node) {
        $custom_entity_node->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function custom_entity_example_user_predelete(UserInterface $account): void {
  // Delete custom_entity_nodes that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('custom_entity_node');
  $custom_entity_node_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($custom_entity_node_ids)
  );
}
